export const PRODUCT_LOAD_IN_PROGRESS = 'PRODUCT_LOAD_IN_PROGRESS';
export const PRODUCT_LOAD_FAIL = 'PRODUCT_LOAD_FAIL';
export const PRODUCT_ADD_BY_ID = 'PRODUCT_ADD_BY_ID';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const GET_PRODUCTS_BY_LIMIT = 'GET_PRODUCTS_BY_LIMIT';
export const LOADING = 'LOADING';
export const INIT_APP = 'INIT_APP';
export const ADD_TO_STORE = 'ADD_TO_STORE';
export const DECREASE_STORE = 'DECREASE_STORE';
export const DELETE_ITEM_FROM_STORE = 'DELETE_ITEM_FROM_STORE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const DECREASE_ITEM_AMOUNT = 'DECREASE_ITEM_AMOUNT';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const REFRESH_CART = 'REFRESH_CART';